"""Data Science Agent for analyzing personal health data.

This module implements the core Data Science Agent that can analyze
health data by generating approaches, code, and interpretations.
"""

from typing import Optional, Tuple, List, Dict, Any
import pandas as pd

from ..llm import LLMBackend, get_llm_backend
from ..tools import PythonSandbox, PhdaPythonRequest, PhdaPythonReply, get_python_sandbox
from ..utils import (
    load_persona,
    serialize_dataframes,
    parse_code_output,
    DFS_INFO,
    DataFrameInfo,
)
from ..prompts import (
    generate_approach_prompt,
    generate_approach_prompt_baseline,
    generate_codegen_prompt,
    generate_codegen_prompt_baseline,
    generate_code_refinement_prompt,
    generate_debug_prompt_baseline,
    generate_debug_prompt_v2,
    generate_result_communication_prompt,
)


def _is_python_stub(approach: str) -> bool:
    """Return True when *approach* is a Python function stub (docstring_prompt format).

    The codegen eval harness passes a fully-formed ``def analysis(...)`` stub
    as the approach, while the production pipeline passes a natural-language
    text description generated by ``generate_approach``. Each format requires
    a different codegen prompt, so this detector gates the routing decision
    in ``generate_code``, ``debug_code``, and ``refine_code``.

    The detector is conservative: it requires both a code-shaped start
    (``def analysis(``, ``from typing import``, or ``import ``) AND a docstring
    (``\"\"\"``) somewhere in the text, so a natural-language approach cannot
    trigger it accidentally.
    """
    s = approach.lstrip()
    has_code_start = (
        s.startswith("from typing import")
        or s.startswith("def analysis(")
        or s.startswith("import ")
    )
    return has_code_start and '"""' in approach


class DataScienceAgent:
    """Data Science Agent for analyzing personal health data.
    
    This agent follows a multi-step process:
    1. Generate an analysis approach from the user query
    2. Generate Python code to implement the approach
    3. Execute the code in a sandbox
    4. Debug/retry if there are errors
    5. Interpret the results for the user
    
    Example:
        ```python
        from pha.agents import DataScienceAgent
        from config import Settings
        
        settings = Settings()
        agent = DataScienceAgent(settings)
        
        response = agent.query("What's my average sleep over the last week?")
        print(response)
        ```
    """
    
    def __init__(
        self,
        settings: Optional["Settings"] = None,  # type: ignore
        llm_backend: Optional[LLMBackend] = None,
        summary_df: Optional[pd.DataFrame] = None,
        activities_df: Optional[pd.DataFrame] = None,
        profile_df: Optional[pd.DataFrame] = None,
        population_df: Optional[pd.DataFrame] = None,
        num_code_retries: int = 3,
        total_code_retries: int = 5,
        max_code_update_cycles: int = 1,
    ):
        """Initialize the Data Science Agent.

        You can either:
        1. Pass a Settings object
        2. Use configure() method after initialization (recommended for consistency)
        3. Pass DataFrames directly via load_dataframes()

        Args:
            settings: Configuration settings (includes paths and API keys).
            llm_backend: Pre-configured LLM backend. If not provided, creates one from settings.
            summary_df: Daily health metrics DataFrame.
            activities_df: Exercise/activity DataFrame.
            profile_df: User profile DataFrame.
            population_df: Population comparison DataFrame.
            num_code_retries: Number of retries per code execution error.
            total_code_retries: Total number of code generation attempts.
            max_code_update_cycles: Max interpreter-driven refinement cycles in
                ``generate_code_with_retry``. Kept separate from error-fix
                retries so a persistent ``[CODE UPDATE]`` response cannot
                consume the full retry budget on working code.
        """
        self.num_code_retries = num_code_retries
        self.total_code_retries = total_code_retries
        self.max_code_update_cycles = max_code_update_cycles
        
        # Initialize LLM as None - can be set via configure()
        self.llm = None
        
        # Initialize DataFrames as None - can be set via load_dataframes()
        self.summary_df = None
        self.activities_df = None
        self.profile_df = None
        self.population_df = None
        self.dfs_str = ""
        self.dfs_info_str = ""
        self.python_sandbox = None
        
        # Set up LLM backend if provided
        if llm_backend is not None:
            self.llm = llm_backend
        elif settings is not None:
            self.llm = get_llm_backend(
                backend_type=settings.llm_backend,
                api_key=settings.get_api_key(),
                model_name=settings.model_name,
                temperature=settings.temperature,
                max_tokens=settings.max_tokens,
            )
        
        # Load data if provided
        if all(df is not None for df in [summary_df, activities_df, profile_df, population_df]):
            self._setup_dataframes(summary_df, activities_df, profile_df, population_df)
        elif settings is not None:
            dfs = load_persona(settings=settings)
            self._setup_dataframes(*dfs)
    
    def _setup_dataframes(
        self,
        summary_df,
        activities_df,
        profile_df,
        population_df,
    ) -> None:
        """Set up DataFrames and related components."""
        self.summary_df = summary_df
        self.activities_df = activities_df
        self.profile_df = profile_df
        self.population_df = population_df
        
        # Serialize DataFrames for prompts
        self.dfs_str = serialize_dataframes(
            [self.summary_df, self.activities_df, self.profile_df, self.population_df],
            DFS_INFO,
        )
        
        # Create DataFrame info string for codegen prompt
        self.dfs_info_str = self._serialize_df_info(DFS_INFO)
        
        # Set up Python sandbox
        self.python_sandbox = get_python_sandbox(
            dfs={
                "summary_df": self.summary_df,
                "activities_df": self.activities_df,
                "profile_df": self.profile_df,
                "population_df": self.population_df,
            }
        )
    
    def configure(
        self,
        api_key: Optional[str] = None,
        provider: Optional[str] = None,
        model_name: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 8192,
        # Legacy parameter for backwards compatibility
        gemini_api_key: Optional[str] = None,
    ) -> "DataScienceAgent":
        """Configure the LLM backend.
        
        Args:
            api_key: API key for the selected provider.
            provider: "gemini", "openai", or "anthropic".
            model_name: Model to use (uses provider defaults if not specified).
            temperature: Sampling temperature.
            max_tokens: Maximum output tokens.
            gemini_api_key: DEPRECATED - use api_key instead.
            
        Returns:
            Self for chaining.
        """
        # Handle legacy parameter
        if gemini_api_key and not api_key:
            api_key = gemini_api_key
            if not provider:
                provider = "gemini"
        
        # If provider not specified, get from global config
        from ..llm.config import get_config
        config = get_config()
        if not provider:
            provider = config.provider
            
        # Update global configuration
        from ..llm.config import configure_global
        configure_global(
            provider=provider,
            api_key=api_key,
            model_name=model_name,
            temperature=temperature,
        )
        
        # Initialize backend
        self.llm = get_llm_backend(
            backend_type=provider,  # type: ignore
            api_key=api_key,
            model_name=model_name,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        
        return self
    
    def load_dataframes(
        self,
        dataframes: Dict[str, Any],
    ) -> "DataScienceAgent":
        """Load DataFrames for analysis.
        
        Args:
            dataframes: Dictionary with keys 'summary', 'activities', 
                       'profile', 'population' mapping to DataFrames.
                       
        Returns:
            Self for chaining.
        """
        summary_df = dataframes.get('summary')
        activities_df = dataframes.get('activities')
        profile_df = dataframes.get('profile')
        population_df = dataframes.get('population')
        
        # Allow partial loading - use existing or empty DataFrames for missing
        if summary_df is None:
            summary_df = self.summary_df if self.summary_df is not None else pd.DataFrame()
        if activities_df is None:
            activities_df = self.activities_df if self.activities_df is not None else pd.DataFrame()
        if profile_df is None:
            profile_df = self.profile_df if self.profile_df is not None else pd.DataFrame()
        if population_df is None:
            population_df = self.population_df if self.population_df is not None else pd.DataFrame()
        
        self._setup_dataframes(summary_df, activities_df, profile_df, population_df)
        
        return self
    
    def _serialize_df_info(self, dfs_info: List[DataFrameInfo]) -> str:
        """Serialize DataFrame info for the codegen prompt."""
        s = ""
        for df_info in dfs_info:
            s += f"**{df_info['name']}**\n"
            s += f"\tdescription: {df_info['description']}\n"
            s += f"\tvariable_name: {df_info['variable_name']}\n"
            s += "\n"
        return s
    
    def _run_llm(self, prompt: str) -> str:
        """Run the LLM and return the response."""
        return self.llm.generate(prompt)

    def _extract_code(self, response: str) -> str:
        """Pull the contents of a ```python ... ``` block out of an LLM response.

        Used only by the baseline / refinement code paths, whose prompts
        explicitly instruct the model to wrap output in a fenced block.
        Not used by the V2 production path (which continues from a function
        signature without fences and relies on ``parse_code_output``).
        """
        code = response.split('```python')[1].split('```')[0]
        return code

    def generate_approach_baseline(self, question: str) -> str:
        """Generate an analysis approach for the baseline / eval path."""
        approach_prompt = generate_approach_prompt_baseline(
            query=question,
        )
        return self._run_llm(approach_prompt)

    def generate_approach(self, question: str) -> str:
        """Generate an analysis approach for the given question.

        Args:
            question: The user's question about their health data.

        Returns:
            The generated approach text.
        """
        approach_prompt = generate_approach_prompt(
            query=question,
            dfs_str=self.dfs_str,
        )
        return self._run_llm(approach_prompt)

    def generate_code(self, question: str, approach: str) -> str:
        """Generate Python code from the approach.

        Routes to the baseline codegen prompt when *approach* is a Python
        function stub (docstring_prompt format used by the eval harness).
        ``CODEGEN_PREAMBLE_V2`` imposes a ``-> Dict[str, Any]`` return type
        and parameter defaults that override the stub's exact return
        specification, causing unit-test failures.  The baseline prompt was
        designed for the stub format and treats the stub as the
        authoritative specification.

        Args:
            question: The original user question.
            approach: The analysis approach (text description or Python stub).

        Returns:
            Generated Python code.
        """
        if _is_python_stub(approach):
            return self.generate_code_baseline(question, approach)

        code_prompt = generate_codegen_prompt(
            query=question,
            approach_str=approach,
            dfs_str=self.dfs_str,
            dfs_info_str=self.dfs_info_str,
        )
        code = self._run_llm(code_prompt)
        return parse_code_output(code)

    def generate_code_baseline(self, question: str, approach: str) -> str:
        """Generate Python code for the baseline / eval path."""
        code_prompt = generate_codegen_prompt_baseline(
            query=question,
            approach_str=approach,
        )
        code = self._run_llm(code_prompt)
        extracted_code = self._extract_code(code)
        return parse_code_output(extracted_code)

    def execute_code(self, code: str) -> PhdaPythonReply:
        """Execute code in the sandbox.

        Args:
            code: Python code to execute.

        Returns:
            Execution result.
        """
        return self.python_sandbox.execute(
            PhdaPythonRequest(request=code, include_traceback_for_errors=True)
        )

    def debug_code(
        self,
        approach: str,
        code_result: PhdaPythonReply,
        code_update_feedback: str = "",
    ) -> str:
        """Generate debugged/fixed code.

        Routes to the baseline debug prompt when *approach* is a Python stub,
        for the same reason as ``generate_code``: ``DEBUG_CODEGEN_PREAMBLE_V2``
        re-imposes structural constraints that override the stub's contract
        on every retry.

        Args:
            approach: The analysis approach (text description or Python stub).
            code_result: Previous execution result.
            code_update_feedback: Optional feedback for code update (ignored
                for stub approaches; the stub is re-specified from scratch).

        Returns:
            Fixed Python code.
        """
        if _is_python_stub(approach):
            return self.debug_code_baseline(approach, code_result)

        debug_prompt = generate_debug_prompt_v2(
            approach_str=approach,
            code=code_result.orig_code,
            code_result=str(code_result.execution_result),
            code_update_feedback=code_update_feedback,
        )
        code = self._run_llm(debug_prompt)
        return parse_code_output(code)

    def debug_code_baseline(self, approach: str, code_result: PhdaPythonReply) -> str:
        """Debug code using the baseline prompt (no code_update_feedback)."""
        code_prompt = generate_debug_prompt_baseline(
            approach_str=approach,
            code=code_result.orig_code,
            error=code_result.execution_result.stderr,
            dfs_str=self.dfs_str,
        )
        code = self._run_llm(code_prompt)
        extracted_code = self._extract_code(code)
        return parse_code_output(extracted_code)

    def refine_code(
        self,
        approach: str,
        code_result: PhdaPythonReply,
        code_update_feedback: str,
    ) -> str:
        """Refine successfully-executing code based on interpreter feedback.

        Unlike ``debug_code`` (which targets execution errors), this is
        called when code ran without error but the interpreter identified a
        logical issue. For Python stub approaches the canonical specification
        is the stub itself; ``CODE_REFINEMENT_PREAMBLE`` carries the V2-style
        structural constraints, so stub approaches fall back to
        ``debug_code_baseline`` which re-implements against the stub without
        imposing a competing signature.

        Args:
            approach: The analysis approach (text description or Python stub).
            code_result: Most recent execution result (successful — no error).
            code_update_feedback: Natural-language refinement request from the
                interpreter.

        Returns:
            Refined Python code.
        """
        if _is_python_stub(approach):
            return self.debug_code_baseline(approach, code_result)

        refine_prompt = generate_code_refinement_prompt(
            approach_str=approach,
            code=code_result.orig_code,
            execution_results=code_result.execution_result.output,
            code_update_feedback=code_update_feedback,
        )
        code = self._run_llm(refine_prompt)
        extracted_code = self._extract_code(code)
        return parse_code_output(extracted_code)

    def generate_code_with_retry_baseline(
        self, query: str, approach: str, max_try: int = 5
    ) -> str:
        """Baseline retry loop: 1 initial generate + (max_try - 1) debug retries."""
        code = self.generate_code_baseline(query, approach)
        code_result = self.execute_code(code)

        for _ in range(max_try - 1):
            if not code_result.has_error():
                break
            code = self.debug_code_baseline(
                approach=approach,
                code_result=code_result,
            )
            code_result = self.execute_code(code)

        return code

    def generate_code_with_retry(
        self,
        query: str,
        approach: str,
        max_try: int = 5,
        max_code_update_cycles: Optional[int] = None,
    ) -> str:
        """Generate and execute code with retry, handling errors and refinement.

        Used by the codegen eval harness as an alternative entry point that
        exposes the full error-fix + refinement loop. The production
        ``query()`` method has its own internal retry loop and does not call
        this.

        Args:
            query: The user's question about their health data.
            approach: The analysis approach (text or stub).
            max_try: Maximum total attempts (1 initial generate + max_try-1
                retries).
            max_code_update_cycles: Cap on interpreter-driven refinement
                cycles. Defaults to ``self.max_code_update_cycles``. Kept
                separate from error-fix retries to prevent a persistent
                ``[CODE UPDATE]`` response from consuming the full retry
                budget on working code.

        Returns:
            The best-executing Python code string seen during the retry loop.
        """
        if max_code_update_cycles is None:
            max_code_update_cycles = self.max_code_update_cycles

        code = self.generate_code(query, approach)
        code_result = self.execute_code(code)
        code_update_feedback = ""
        code_update_count = 0
        best_code = code if not code_result.has_error() else None

        for _ in range(max_try - 1):
            if code_result.has_error():
                # Real execution error: error-fixing debug prompt.
                # Any pending refinement feedback is discarded — fixing the
                # crash takes priority.
                code = self.debug_code(
                    approach=approach,
                    code_result=code_result,
                )
                code_update_feedback = ""
                code_result = self.execute_code(code)
            elif code_update_feedback:
                # Code ran successfully but interpreter flagged a logical
                # issue — use the dedicated refinement prompt.
                code = self.refine_code(
                    approach=approach,
                    code_result=code_result,
                    code_update_feedback=code_update_feedback,
                )
                code_update_feedback = ""
                code_update_count += 1
                code_result = self.execute_code(code)

            if not code_result.has_error():
                best_code = code
                if code_update_count < max_code_update_cycles:
                    interpretation = self.interpret_results(
                        question=query,
                        approach=approach,
                        code=code,
                        execution_results=code_result.execution_result.output,
                    )
                    if interpretation.lstrip().startswith("[CODE UPDATE]"):
                        code_update_feedback = interpretation.split("[CODE UPDATE]")[-1].strip()
                    else:
                        break
                else:
                    break

        return best_code if best_code is not None else code


    def interpret_results(
        self,
        question: str,
        approach: str,
        code: str,
        execution_results: str,
    ) -> str:
        """Interpret execution results for the user.
        
        Args:
            question: Original user question.
            approach: Analysis approach.
            code: Executed code.
            execution_results: Results from code execution.
            
        Returns:
            User-friendly interpretation or code update request.
        """
        prompt = generate_result_communication_prompt(
            query=question,
            approach_str=approach,
            code=code,
            execution_results=execution_results,
        )
        return self._run_llm(prompt)
    
    def query(self, question: str) -> str:
        """Process a user question end-to-end.
        
        This is the main entry point for using the agent. It:
        1. Generates an approach
        2. Generates and executes code
        3. Retries on errors
        4. Returns an interpreted result
        
        Args:
            question: The user's question about their health data.
            
        Returns:
            A user-friendly response summarizing the analysis.
        """
        from datetime import datetime
        from pha.streaming import emit_step
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"\n[DS:{ts}] ═══ DataScienceAgent.query ═══")
        print(f"[DS:{ts}] Question: {question[:100]}...")
        
        # Step 1: Generate approach
        emit_step("DS", "Generating analysis approach...")
        print(f"[DS:{ts}] Step 1: Generating approach...")
        approach = self.generate_approach(question)
        print(f"[DS:{ts}] Approach ({len(approach)} chars): {approach[:200]}...")
        
        # Step 2: Generate initial code
        emit_step("DS", "Writing analysis code...")
        print(f"[DS:{ts}] Step 2: Generating code...")
        code = self.generate_code(question, approach)
        print(f"[DS:{ts}] Code ({len(code)} chars):\n{code[:300]}")
        
        # Step 3: Execute code
        emit_step("DS", "Executing analysis code...")
        print(f"[DS:{ts}] Step 3: Executing code...")
        code_result = self.execute_code(code)
        has_err = code_result.has_error()
        output = code_result.execution_result.output
        print(f"[DS:{ts}] Execution: error={has_err}, output ({len(output)} chars): {output[:200]}...")
        
        # Step 4: Debug loop
        num_total_steps = 0
        code_update_feedback = ""
        
        while num_total_steps < self.total_code_retries:
            num_total_steps += 1
            
            # If there's an error or feedback, try to fix
            if code_result.has_error() or code_update_feedback:
                emit_step("DS", f"Debugging code (attempt {num_total_steps})...")
                print(f"[DS:{ts}] Debug loop iteration {num_total_steps}: error={code_result.has_error()}, feedback={bool(code_update_feedback)}")
                for retry in range(self.num_code_retries):
                    code = self.debug_code(
                        approach=approach,
                        code_result=code_result,
                        code_update_feedback=code_update_feedback,
                    )
                    print(f"[DS:{ts}]   Retry {retry+1}: new code ({len(code)} chars)")
                    code_result = self.execute_code(code)
                    code_update_feedback = ""
                    
                    has_err = code_result.has_error()
                    output = code_result.execution_result.output
                    print(f"[DS:{ts}]   Retry {retry+1}: error={has_err}, output: {output[:150]}...")
                    
                    if not code_result.has_error():
                        break
            
            # Step 5: Interpret results
            emit_step("DS", "Interpreting results...")
            print(f"[DS:{ts}] Step 5: Interpreting results...")
            result_communication = self.interpret_results(
                question=question,
                approach=approach,
                code=code,
                execution_results=code_result.execution_result.output,
            )
            
            # Check if interpretation requests code update
            if result_communication.lstrip().startswith("[CODE UPDATE]"):
                code_update_feedback = result_communication.split("[CODE UPDATE]")[-1].strip()
                print(f"[DS:{ts}] Interpretation requested CODE UPDATE: {code_update_feedback[:100]}...")
            else:
                # Success - return the summary
                print(f"[DS:{ts}] ✓ Final response ({len(result_communication)} chars): {result_communication[:200]}...")
                return result_communication
        
        # If we exhausted retries, return whatever we have
        print(f"[DS:{ts}] ✗ Exhausted {self.total_code_retries} retries, returning last result")
        return result_communication
    
    def query_with_details(self, question: str) -> dict:
        """Process a user question and return detailed results.
        
        Like query(), but returns all intermediate results for debugging
        or detailed analysis.
        
        Args:
            question: The user's question about their health data.
            
        Returns:
            Dictionary containing:
                - question: Original question
                - approach: Generated approach
                - code: Final code
                - execution_result: Raw execution result
                - response: Final interpreted response
        """
        approach = self.generate_approach(question)
        code = self.generate_code(question, approach)
        code_result = self.execute_code(code)
        
        # Simple version without retries for detailed output
        response = self.interpret_results(
            question=question,
            approach=approach,
            code=code,
            execution_results=code_result.execution_result.output,
        )
        
        return {
            "question": question,
            "approach": approach,
            "code": code,
            "execution_result": {
                "output": code_result.execution_result.output,
                "stderr": code_result.execution_result.stderr,
                "status": code_result.execution_result.status.value,
            },
            "response": response,
        }
